added some file to it
ahadsheikh/PhytoChem pull request #6
Opened 2020-11-02 17:59 UTC by SohanCSERU

2020-11-02 18:00 UTC, SohanCSERU commented
Check it

2020-11-03 05:57 UTC, SohanCSERU commented
**I reviewed ... and i think now it is well ...**

2020-11-03 11:10 UTC, ahadsheikh requested changes

2020-11-03 11:10 UTC, ahadsheikh commented on main/static/main/CSS/style.css
> +	background:  url('{{ STATIC_URL }}main/images/Search-icon.png') no-repeat center center, #1E1E20;
this line should be `background:  url("../images/Search-icon.png") no-repeat center center, #1E1E20;`

2020-11-03 11:10 UTC, ahadsheikh commented on main/static/main/CSS/style.css
> +	background:  url('{{ STATIC_URL }}main/images/Search-icon.png') no-repeat center center, #1E1E20;
this line should be `background:  url("../images/Search-icon.png") no-repeat center center, #1E1E20;`

2020-11-03 15:30 UTC, SohanCSERU reviewed
Everything is al right

2020-11-03 15:51 UTC, merged

2020-11-03 16:10 UTC, ahadsheikh commented
Done